repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.4
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_docs

  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.447  # Latest stable Checkov
    hooks:
      - id: checkov
        args: ["--hard-fail-on", "HIGH"]

  - repo: https://github.com/aquasecurity/tfsec
    rev: v1.28.14  # Latest stable tfsec
    hooks:
      - id: tfsec
        args: ["--minimum-severity", "HIGH"]
