name: Pre-commit checks

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - uses: hashicorp/setup-terraform@v3

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
