name: Pre-commit checks

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install the latest version of Python
      - name: Setup Python
        uses: actions/setup-python@v5

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Install the latest version of tflint
      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v4

      # Run the pre-commit hooks
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
